apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spring-boot-kubernetes
    spec:
      containers:
        - name: spring-boot-kubernetes
          image: spring-boot-kubernetes:1.0.0
          imagePullPolicy: Never #just for minikube,do not use this in production!!!
          ports:
            - containerPort: 8080